language: cpp
sudo: false

compiler:
  - gcc-4.8
  - gcc-5
  - clang-3.7

env:
  - TEST="all"
  - TEST="some"
  - TEST="none"
  
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gsl-bin
    - libgsl0-dev
    - libfftw3-dev
    - cmake
    - cmake-data
    - python-numpy
    - g++-4.8
    - g++-5
    - clang-3.7

script:
  - env
  - set
